### ISSUE TITLE
Macathena Logo

### ISSUE THREAD

**Issue by leee** [macathena/macathena#5]
The uh... best I could do.

![macos](https://cloud.githubusercontent.com/assets/963328/19357687/ada60466-9140-11e6-909c-0313ac24117c.png)

**Comment by leee** [comment]
```
   leee / macathena / bookwyrm + 2016-10-13 12:41:44 [zmirrorp.zulipchat.net / Jacquie]
       I'm working on a logo
```

**Comment by glasswyrm** [comment]
Is this terrible?
<img width="315" alt="macathena logo 02" src="https://cloud.githubusercontent.com/assets/22819491/19359941/57596a4e-914a-11e6-8a0d-d8f7afca0460.png">

**Comment by tthoma24** [comment]
I like it, but it may be a violation of Apple’s IP guidelines

http://www.apple.com/legal/intellectual-property/guidelinesfor3rdparties.html <http://www.apple.com/legal/intellectual-property/guidelinesfor3rdparties.html>

**Comment by glasswyrm** [comment]
Ah, probably.
So an owl eating an apple would be Right Out?

**Comment by leee** [comment]
@glasswyrm - oh my lord yes this is so beautiful and cute at the same time!

Unsure but maybe we may want to keep the `X` and punt the circle gradient to flatten the image, so to speak, but you're in charge here.

@tthoma24 - from a quick reading, I think we may be fine per `Authorized Use of Apple Trademarks//Compatibility//b`, but to steer clear of any potential infringement, as the project becomes mature enough for a release, we should contact Apple's Copyright Team and probably enter a trademark agreement with their Software Licensing Department.

**Comment by glasswyrm** [comment]
Sure, I can take out the gradient and just make it a circle.
Also below see totally serious alternate image idea.
![hungrie liek teh wol](https://cloud.githubusercontent.com/assets/22819491/19360275/d8083d4a-914b-11e6-8bd2-4753399e527e.jpg)

**Comment by tthoma24** [comment]
@leee, if we do go that route, it’s likely something to contact TLO about when the time comes

**Comment by leee** [comment]
@tthoma24 - I thought TLO specifically handles licensing/investments of IP, and this particular matter at hand. Wouldn't the OGC (and even the BU law clinics) be a better resource?

**Comment by leee** [comment]
@glasswyrm - that logo is so terrible that it actually looks good... Apple would totally be fine with us using that, right!? :^)

**Comment by glasswyrm** [comment]
After reading through the legalese a couple times, the only thing I feel comfortable saying is that the word 'Macathena' is ok. I'll try to make something incorporating that so we have a fallback.
<img width="315" alt="macathena logo 03" src="https://cloud.githubusercontent.com/assets/22819491/19360877/55207d0e-914e-11e6-8937-b16210fd3b09.png">

**Comment by glasswyrm** [comment]
Not a huge fan of either, but thoughts?
![macathena logo 05](https://cloud.githubusercontent.com/assets/22819491/19368123/852667ac-916c-11e6-94f3-ac1364fb4ed6.jpg)
![macathena logo 04](https://cloud.githubusercontent.com/assets/22819491/19368122/8524917a-916c-11e6-9387-3fef502c0149.jpg)

**Comment by leee** [comment]
@glasswyrm - I've adopted the "owl+words" logo for the time being as the GitHub organization's logo, hooray! It's so adorable and the owl is just looking at oneself all innocent-like, unknowing of the terribleness we will have it go through with the introduction of new Macathena. :^)

If there are no objections, I move to close this github issue now - I believe @glasswyrm may wish to punt the current raster logo for a vectorized one, but I'd suppose that is more of an `enhancement` than an initial `feature/addition`.

Thank you again, @glasswyrm!

**Comment by glasswyrm** [comment]
Here's the vectorized copy.
[macathena logo 05.eps.zip](https://github.com/macathena/macathena/files/529803/macathena.logo.05.eps.zip)

**Comment by leee** [comment]
@glasswyrm pushed to https://github.com/macathena/logo with the author of the commit set as you (your MIT address, that is) - let me know if there's another address I should've used (because the commit doesn't have that email associated with your GitHub profile).
